services:
  parser-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # main project folder mount
      - ..:/home/developer/develop
      # ssh keys mount
      - ${HOME}/.ssh:/home/developer/.ssh
      # docker socket mount
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - USER=developer
      - UID
  